### ISSUE TITLE
NullPointerException Exception on client

### ISSUE THREAD

**Issue by nekomeowww** [nekomeowww/CustomDrones#2]
This exception only existed on the server, however after we fixed the server NPE, the client went wrong.

```
java.lang.NullPointerException
	at com.github.nekomeowww.customdrones.entity.EntityDroneBaby.initSpawnSetAppearance(EntityDroneBaby.java:52) ~[EntityDroneBaby.class:?]
	at com.github.nekomeowww.customdrones.entity.EntityDroneMob.initDroneInfo(EntityDroneMob.java:95) ~[EntityDroneMob.class:?]
	at com.github.nekomeowww.customdrones.entity.EntityDroneBaby.initDroneInfo(EntityDroneBaby.java:47) ~[EntityDroneBaby.class:?]
	at com.github.nekomeowww.customdrones.entity.EntityDroneMob.onInitSpawn(EntityDroneMob.java:88) ~[EntityDroneMob.class:?]
	at com.github.nekomeowww.customdrones.entity.EntityDroneMob.onInitialSpawn(EntityDroneMob.java:78) ~[EntityDroneMob.class:?]
	at net.minecraft.world.WorldEntitySpawner.performWorldGenSpawning(WorldEntitySpawner.java:283) ~[WorldEntitySpawner.class:?]
	at net.minecraft.world.gen.ChunkProviderOverworld.populate(ChunkProviderOverworld.java:454) ~[ChunkProviderOverworld.class:?]
	at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1078) ~[Chunk.class:?]
	at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1061) ~[Chunk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:161) ~[ChunkProviderServer.class:?]
	at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:337) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:107) ~[IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:124) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by nekomeowww** [comment]
Crash fixed for ```1.6.1 Beta B3``` on commit [cc69588](https://github.com/nekomeowww/CustomDrones/commit/cc6958882d3d2566ee61f7672d5aff5988c3ffd9)
