### ISSUE TITLE
NoClassDefFoundError found on server load up

### ISSUE THREAD

**Issue by nekomeowww** [nekomeowww/CustomDrones#3]
```
java.lang.NoClassDefFoundError: Could not initialize class com.github.nekomeowww.customdrones.render.DroneModels
        at com.github.nekomeowww.customdrones.entity.EntityDroneBaby.initSpawnSetAppearance(EntityDroneBaby.java:52)
        at com.github.nekomeowww.customdrones.entity.EntityDroneMob.initDroneInfo(EntityDroneMob.java:95)
        at com.github.nekomeowww.customdrones.entity.EntityDroneBaby.initDroneInfo(EntityDroneBaby.java:47)
        at com.github.nekomeowww.customdrones.entity.EntityDroneMob.onInitSpawn(EntityDroneMob.java:88)
        at com.github.nekomeowww.customdrones.entity.EntityDroneMob.func_180482_a(EntityDroneMob.java:78)
        at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:275)
        at net.minecraft.world.gen.ChunkProviderOverworld.func_185931_b(ChunkProviderOverworld.java:454)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:268)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nekomeowww** [comment]
Seems the new NullPointerException replaced the NoClassDefFoundError when debugging today.
Furthur test is required.

**Comment by nekomeowww** [comment]
@zhangyubaka
